export default [
  {
    id: 73390,
    owner: 'Botify',
    projectSlug: 'Galaxy',
    analysisSlug: 'Demo-300k',
    env: 'production',
    url: '',
    crawledUrls: 5236,
    knownUrls: 5236,
    links: 219093,
    segmentsName: ['PageType'],
    exports: {
      ALL_URL_DETAILS: 'https://d121xa69ioyktv.cloudfront.net/advanced_exports/uncompressed/botify-galaxy-demo-300k-urls.csv',
      ALL_LINKS: 'https://d121xa69ioyktv.cloudfront.net/advanced_exports/uncompressed/botify-galaxy-demo-300k-links.csv',
    },
  },
  {
    id: 88932,
    owner: 'Botify',
    projectSlug: 'Galaxy',
    analysisSlug: 'Demo-1M',
    env: 'production',
    url: '',
    crawledUrls: 26560,
    knownUrls: 26560,
    links: 1107395,
    extractsName: ['Breadcrumb', 'Nb Shares', 'Nb Products'],
    segmentsName: ['PageType'],
    exports: {
      ALL_URL_DETAILS: 'https://d121xa69ioyktv.cloudfront.net/advanced_exports/uncompressed/botify-galaxy-demo-1M-urls.csv',
      ALL_LINKS: 'https://d121xa69ioyktv.cloudfront.net/advanced_exports/uncompressed/botify-galaxy-demo-1M-links.csv',
    },
  },
  {
    id: 91558,
    owner: 'Botify',
    projectSlug: 'Galaxy',
    analysisSlug: 'Demo-12M',
    env: 'production',
    crawledUrls: 135969,
    knownUrls: 135969,
    links: 12506098,
    extractsName: ['Breadcrumb'],
    segmentsName: ['PageType'],
    exports: {
      ALL_URL_DETAILS: 'https://d121xa69ioyktv.cloudfront.net/advanced_exports/uncompressed/botify-galaxy-demo-12M-urls.csv',
      ALL_LINKS: 'https://d121xa69ioyktv.cloudfront.net/advanced_exports/uncompressed/botify-galaxy-demo-12M-links.csv',
    },
  }
];
